from typing import TypedDict, Annotated, List, Dict
import operator

def add_tokens(existing: Dict[str, int], new: Dict[str, int]) -> Dict[str, int]:
    if existing is None:
         existing = {}
    if new is None:
         new = {}
    result = existing.copy()
    for k, v in new.items():
        result[k] = result.get(k, 0) + v
    return result

class TaskState(TypedDict):
    """
    Represents the shared state payload as it flows through the LangGraph topologies.
    """
    task_id: str
    task_description: str
    tests: List[str]            # The unit tests for this MBPP task
    
    plan: str                   # Generated by Planner
    code: str                   # Generated by Coder
    review_comments: List[str]  # Generated by Reviewer
    test_results: List[str]     # Generated by Tester / Sandbox
    test_passed: bool           # Outcome Y in {pass, fail}
    
    iterations: Annotated[int, operator.add]
    token_usage: Annotated[Dict[str, int], add_tokens]
